<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_81fQEHSKEeyBDs9WqzSppA" name="AukcijaDiagram" author="Stefan" bonitaVersion="7.13.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_81fQEXSKEeyBDs9WqzSppA" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_81fQEnSKEeyBDs9WqzSppA" name="Kupac" actor="_81fQK3SKEeyBDs9WqzSppA">
        <elements xmi:type="process:StartEvent" xmi:id="_81fQE3SKEeyBDs9WqzSppA" name="Start1" outgoing="_81fQKHSKEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_81fQFHSKEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_81fQFXSKEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_81fQFnSKEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_81fQF3SKEeyBDs9WqzSppA" name="Kupac salje zahtev" outgoing="_js2iQHSLEeyBDs9WqzSppA" incoming="_81fQKHSKEeyBDs9WqzSppA _JuLKAHScEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_81fQGHSKEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_81fQGXSKEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_81fQGnSKEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_81fQG3SKEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_81fQHHSKEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_81fQHXSKEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_81fQHnSKEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_81fQH3SKEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_81fQIHSKEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_81fQIXSKEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_81fQInSKEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_81fQI3SKEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_LP8HcHSLEeyBDs9WqzSppA" name="imaNemaOdgovarajucih" outgoing="__G9G8HSLEeyBDs9WqzSppA _KjKEgHSMEeyBDs9WqzSppA _U1p9IHSOEeyBDs9WqzSppA" incoming="_pZUV0HSLEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LP8HcnSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LP8HcXSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_LP8Hc3SLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_OdaJAHSLEeyBDs9WqzSppA" name="End1" incoming="__2K9YHSLEeyBDs9WqzSppA _Y7ip4HSNEeyBDs9WqzSppA _VxeykHSWEeyBDs9WqzSppA _VLCVQHSkEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OdaJAnSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OdaJAXSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OdaJA3SLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ZDbsgHSLEeyBDs9WqzSppA" name="Sistem trazi odgovarajuce prodavce" outgoing="_pZUV0HSLEeyBDs9WqzSppA" incoming="_js2iQHSLEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZDcTkXSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZDcTkHSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZDcTknSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZDcTk3SLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZDcTlHSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZDcTlXSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZDcTl3SLEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZDcTlnSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_2_i68HSLEeyBDs9WqzSppA" name="Notifikovanje korisnika o nemanju trazenih prodavaca" outgoing="__2K9YHSLEeyBDs9WqzSppA" incoming="__G9G8HSLEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2_i68nSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2_i68XSLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2_i683SLEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2_i69HSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2_i69XSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2_i69nSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2_i6-HSLEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2_i693SLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_HlSlMHSMEeyBDs9WqzSppA" name="Notifikovanje korisnika o manjem broju prodavaca" outgoing="_VMh28HSMEeyBDs9WqzSppA" incoming="_KjKEgHSMEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HlSlMnSMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HlSlMXSMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HlSlM3SMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HlSlNHSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HlSlNXSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HlSlNnSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HlSlOHSMEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HlSlN3SMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_SrQ0EHSMEeyBDs9WqzSppA" name="Korisnik prihvata ili odbija manjak prodavaca" outgoing="_zpwOYHSMEeyBDs9WqzSppA" incoming="_VMh28HSMEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SrQ0EnSMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SrQ0EXSMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SrQ0E3SMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SrQ0FHSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SrQ0FXSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SrQ0FnSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SrQ0GHSMEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SrQ0F3SMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_SrQ0GnSMEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_SrQ0G3SMEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_SrQ0GXSMEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_SrQ0HHSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_zP_qkHSMEeyBDs9WqzSppA" outgoing="_DdJOoHSNEeyBDs9WqzSppA _Y7ip4HSNEeyBDs9WqzSppA" incoming="_zpwOYHSMEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zP_qknSMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zP_qkXSMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zP_qk3SMEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_XhoQoHSNEeyBDs9WqzSppA" name="Slanje emaila odgovarajucim prodavcima" outgoing="_GajwEHSPEeyBDs9WqzSppA" incoming="_DdJOoHSNEeyBDs9WqzSppA _U1p9IHSOEeyBDs9WqzSppA _C3-LYHSVEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XhoQonSNEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XhoQoXSNEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XhoQo3SNEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XhoQpHSNEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XhoQpXSNEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XhoQpnSNEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XhoQqHSNEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XhoQp3SNEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_bqNA0HSTEeyBDs9WqzSppA" name="Sistem salje mejl o tome koliko ponuda ima manje od trazenog" outgoing="_Rzou4HSUEeyBDs9WqzSppA" incoming="_25A7gHSTEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vWJccnSSEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vWJccXSSEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vWJcc3SSEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_vWJcdHSSEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_vWJcdXSSEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vWJcdnSSEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_vWJceHSSEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_vWJcd3SSEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_QS2RkHSUEeyBDs9WqzSppA" name="Kupac odlucuje da li zeli jos ponuda ili je dovoljan broj ponuda" outgoing="_ePE74HSUEeyBDs9WqzSppA" incoming="_Rzou4HSUEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QS2RknSUEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QS2RkXSUEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QS2Rk3SUEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QS2RlHSUEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QS2RlXSUEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QS2RlnSUEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QS2RmHSUEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QS2Rl3SUEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QS2RmnSUEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_QS2Rm3SUEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QS2RmXSUEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QS2RnHSUEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_dAFZMHSUEeyBDs9WqzSppA" name="Gateway2" outgoing="_C3-LYHSVEeyBDs9WqzSppA _LczdwHSWEeyBDs9WqzSppA _3JD68HSZEeyBDs9WqzSppA" incoming="_ePE74HSUEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dAPKMXSUEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dAPKMHSUEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dAPKMnSUEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_M1HUgHSWEeyBDs9WqzSppA" name="Klijent produzava rok ili povlaci zahtev" outgoing="_UHyQ4HSWEeyBDs9WqzSppA" incoming="_LczdwHSWEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_LcpswnSWEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_LcpswXSWEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Lcpsw3SWEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_LcpsxHSWEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_LcpsxXSWEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_LcpsxnSWEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_LcpsyHSWEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Lcpsx3SWEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_M1HUinSWEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_M1HUi3SWEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_M1HUiXSWEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_M1HUjHSWEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Udy9IHSWEeyBDs9WqzSppA" name="Gateway3" outgoing="_VxeykHSWEeyBDs9WqzSppA _wwsVkHSXEeyBDs9WqzSppA" incoming="_UHyQ4HSWEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UHof4nSWEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UHof4XSWEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UHof43SWEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_D7-pQHSZEeyBDs9WqzSppA" name="Kupac razmatra ponude" outgoing="_dCDq8HSbEeyBDs9WqzSppA" incoming="_MqFMYHSaEeyBDs9WqzSppA _gC-2kHShEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D7-pQnSZEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D7-pQXSZEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D7-pQ3SZEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D7-pRHSZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D7-pRXSZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D7-pRnSZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D7-pSHSZEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D7-pR3SZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_qpc_oHSZEeyBDs9WqzSppA" name="Sistem formira rang listu svih ponuda i prosledjuje je kupcu" outgoing="_MqFMYHSaEeyBDs9WqzSppA" incoming="_qpmJkHSZEeyBDs9WqzSppA _3JD68HSZEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qpc_onSZEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qpc_oXSZEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qpc_o3SZEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qpc_pHSZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qpc_pXSZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qpc_pnSZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qpc_qHSZEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qpc_p3SZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_doeKsHSbEeyBDs9WqzSppA" name="Gateway4" outgoing="_JuLKAHScEeyBDs9WqzSppA _z-8oDHScEeyBDs9WqzSppA _6WRPHHSfEeyBDs9WqzSppA" incoming="_dCDq8HSbEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dB6hAnSbEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dB6hAXSbEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dB6hA3SbEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_uLgs8HSgEeyBDs9WqzSppA" name="Kupac salje zahtev za pojasnjenje" outgoing="_6aNecHSgEeyBDs9WqzSppA" incoming="_6WRPHHSfEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6WRPEnSfEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6WRPEXSfEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6WRPE3SfEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6WRPFHSfEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6WRPFXSfEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6WRPFnSfEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6WRPGHSfEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6WRPF3SfEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_uLhUCXSgEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_uLhUCnSgEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_uLhUCHSgEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_uLh7EHSgEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_COghMHShEeyBDs9WqzSppA" name="Kupac donosi odluku da li zeli tog prodavca" outgoing="_VQSwGHShEeyBDs9WqzSppA" incoming="_Bg0UwHShEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BgrK0nShEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BgrK0XShEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BgrK03ShEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BgrK1HShEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BgrK1XShEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BgrK1nShEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BgrK2HShEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BgrK13ShEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_COghOnShEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_COghO3ShEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_COghOXShEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_COghPHShEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_VQSwEHShEeyBDs9WqzSppA" name="Gateway5" outgoing="_gC-2kHShEeyBDs9WqzSppA _hqwFoHShEeyBDs9WqzSppA" incoming="_VQSwGHShEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VQSwEnShEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VQSwEXShEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VQSwE3ShEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_i8YasHSjEeyBDs9WqzSppA" name="Kupac potvrdjuje izvrsenje posla i ocenjuje prodavca" outgoing="_JPZCoHSkEeyBDs9WqzSppA" incoming="_h68L0HSjEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_h6ya0nSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_h6ya0XSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_h6ya03SjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_h6ya1HSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_h6ya1XSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_h6ya1nSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_h6ya2HSjEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_h6ya13SjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_i8YaunSjEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_i8Yau3SjEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_i8YauXSjEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_i8YavHSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_HYcvIHSkEeyBDs9WqzSppA" name="Gateway7" outgoing="_VLCVQHSkEeyBDs9WqzSppA" incoming="_HYcvKHSkEeyBDs9WqzSppA _JPZCoHSkEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HYcvInSkEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HYcvIXSkEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HYcvI3SkEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="__sLwYHSKEeyBDs9WqzSppA" name="Prodavac">
        <elements xmi:type="process:Task" xmi:id="_85EywHSOEeyBDs9WqzSppA" name="Prodavci popunjavaju zahteve ili odustaju" outgoing="_maDNsHSeEeyBDs9WqzSppA" incoming="_GajwEHSPEeyBDs9WqzSppA _wwsVkHSXEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_85EywnSOEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_85EywXSOEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_85Eyw3SOEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_85EyxHSOEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_85EyxXSOEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_85EyxnSOEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_85EyyHSOEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_85Eyx3SOEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_85EyynSOEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_85Eyy3SOEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_85EyyXSOEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_85EyzHSOEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ZadoQHSSEeyBDs9WqzSppA" name="Gateway1" outgoing="_25A7gHSTEeyBDs9WqzSppA _qpmJkHSZEeyBDs9WqzSppA" incoming="_3YKVoHSTEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZadoQnSSEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZadoQXSSEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZadoQ3SSEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_0nLGoHSREeyBDs9WqzSppA" name="Sistem prikuplja ponude i prebrojava ih" outgoing="_3YKVoHSTEeyBDs9WqzSppA" incoming="_maDNsHSeEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0nLGonSREeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0nLGoXSREeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0nLGo3SREeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_0nLGpHSREeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_0nLGpXSREeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_0nLGpnSREeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_0nLGqHSREeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_0nLGp3SREeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5bM1UHScEeyBDs9WqzSppA" name="Prodavac potvrdjuje prihvatanje posla i utvrdjuje termin pocetka izvrsavanja zahteva" outgoing="_GdVAIHSjEeyBDs9WqzSppA" incoming="_z-8oDHScEeyBDs9WqzSppA _hqwFoHShEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_z-8oAnScEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_z-8oAXScEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_z-8oA3ScEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_z-8oBHScEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_z-8oBXScEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_z-8oBnScEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_z-8oCHScEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_z-8oB3ScEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5bODdnScEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_5bODd3ScEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5bODdXScEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5bODeHScEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_2fyQQHSgEeyBDs9WqzSppA" name="Prodavac odgovara na pitanja" outgoing="_Bg0UwHShEeyBDs9WqzSppA" incoming="_6aNecHSgEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2fyQQnSgEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2fyQQXSgEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2fyQQ3SgEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2fyQRHSgEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2fyQRXSgEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2fyQRnSgEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2fyQSHSgEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2fyQR3SgEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_2fyQSnSgEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_2fyQS3SgEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_2fyQSXSgEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_2fyQTHSgEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_GdLPIHSjEeyBDs9WqzSppA" name="sistem potvrdjuje prodavcu da je kupac izabrao njega" outgoing="_2XRGHHSjEeyBDs9WqzSppA" incoming="_GdVAIHSjEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GdLPInSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GdLPIXSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GdLPI3SjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GdLPJHSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GdLPJXSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GdLPJnSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GdLPKHSjEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GdLPJ3SjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_hNIDkHSjEeyBDs9WqzSppA" name="Gateway6" outgoing="_h68L0HSjEeyBDs9WqzSppA _n5TArHSjEeyBDs9WqzSppA" incoming="_3IvmUHSjEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hNIDknSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hNIDkXSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hNIDk3SjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_poOnoHSjEeyBDs9WqzSppA" name="Prodavac ocenjuje kupca" outgoing="_HYcvKHSkEeyBDs9WqzSppA" incoming="_n5TArHSjEeyBDs9WqzSppA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_n5TAonSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_n5TAoXSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_n5TAo3SjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_n5TApHSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_n5TApXSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_n5TApnSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_n5TAqHSjEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_n5TAp3SjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_poOnqnSjEeyBDs9WqzSppA">
            <targetForm xmi:type="expression:Expression" xmi:id="_poOnq3SjEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_poOnqXSjEeyBDs9WqzSppA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_poOnrHSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_2XRGEHSjEeyBDs9WqzSppA" name="Sistem ceka zavrsetak roka za sledeci korak" outgoing="_3IvmUHSjEeyBDs9WqzSppA" incoming="_2XRGHHSjEeyBDs9WqzSppA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_2XRGEnSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_2XRGEXSjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_2XRGE3SjEeyBDs9WqzSppA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_2XRGFHSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_2XRGFXSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_2XRGFnSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_2XRGGHSjEeyBDs9WqzSppA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_2XRGF3SjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_81fQJHSKEeyBDs9WqzSppA">
        <targetForm xmi:type="expression:Expression" xmi:id="_81fQJXSKEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_81fQJnSKEeyBDs9WqzSppA">
        <targetForm xmi:type="expression:Expression" xmi:id="_81fQJ3SKEeyBDs9WqzSppA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_81fQKHSKEeyBDs9WqzSppA" target="_81fQF3SKEeyBDs9WqzSppA" source="_81fQE3SKEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_81fQKXSKEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_81fQKnSKEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_js2iQHSLEeyBDs9WqzSppA" target="_ZDbsgHSLEeyBDs9WqzSppA" source="_81fQF3SKEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_js2iQXSLEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_js2iQnSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pZUV0HSLEeyBDs9WqzSppA" target="_LP8HcHSLEeyBDs9WqzSppA" source="_ZDbsgHSLEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pZUV0XSLEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_pZUV0nSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__G9G8HSLEeyBDs9WqzSppA" target="_2_i68HSLEeyBDs9WqzSppA" source="_LP8HcHSLEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__G9G8XSLEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="__G9G8nSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__2K9YHSLEeyBDs9WqzSppA" target="_OdaJAHSLEeyBDs9WqzSppA" source="_2_i68HSLEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__2K9YXSLEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="__2K9YnSLEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KjKEgHSMEeyBDs9WqzSppA" target="_HlSlMHSMEeyBDs9WqzSppA" source="_LP8HcHSLEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KjKEgXSMEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_KjKEgnSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VMh28HSMEeyBDs9WqzSppA" target="_SrQ0EHSMEeyBDs9WqzSppA" source="_HlSlMHSMEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VMh28XSMEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VMh28nSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zpwOYHSMEeyBDs9WqzSppA" target="_zP_qkHSMEeyBDs9WqzSppA" source="_SrQ0EHSMEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zpwOYXSMEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_zpwOYnSMEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DdJOoHSNEeyBDs9WqzSppA" target="_XhoQoHSNEeyBDs9WqzSppA" source="_zP_qkHSMEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DdJOoXSNEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_DdJOonSNEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Y7ip4HSNEeyBDs9WqzSppA" target="_OdaJAHSLEeyBDs9WqzSppA" source="_zP_qkHSMEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Y7ip4XSNEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Y7ip4nSNEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_U1p9IHSOEeyBDs9WqzSppA" name="pronadjeni odgovarajuci prodavci" target="_XhoQoHSNEeyBDs9WqzSppA" source="_LP8HcHSLEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_U1p9IXSOEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_U1p9InSOEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GajwEHSPEeyBDs9WqzSppA" target="_85EywHSOEeyBDs9WqzSppA" source="_XhoQoHSNEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GajwEXSPEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_GajwEnSPEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_25A7gHSTEeyBDs9WqzSppA" name="nema dovoljno ponuda" target="_bqNA0HSTEeyBDs9WqzSppA" source="_ZadoQHSSEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_25A7gXSTEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_25A7gnSTEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3YKVoHSTEeyBDs9WqzSppA" target="_ZadoQHSSEeyBDs9WqzSppA" source="_0nLGoHSREeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3YKVoXSTEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3YKVonSTEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Rzou4HSUEeyBDs9WqzSppA" target="_QS2RkHSUEeyBDs9WqzSppA" source="_bqNA0HSTEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Rzou4XSUEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Rzou4nSUEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ePE74HSUEeyBDs9WqzSppA" target="_dAFZMHSUEeyBDs9WqzSppA" source="_QS2RkHSUEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ePE74XSUEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ePE74nSUEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_C3-LYHSVEeyBDs9WqzSppA" name="kupac zeli jos ponuda" target="_XhoQoHSNEeyBDs9WqzSppA" source="_dAFZMHSUEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_C3-LYXSVEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_C3-LYnSVEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LczdwHSWEeyBDs9WqzSppA" name="nema ponuda" target="_M1HUgHSWEeyBDs9WqzSppA" source="_dAFZMHSUEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LczdwXSWEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_LczdwnSWEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UHyQ4HSWEeyBDs9WqzSppA" target="_Udy9IHSWEeyBDs9WqzSppA" source="_M1HUgHSWEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UHyQ4XSWEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_UHyQ4nSWEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VxeykHSWEeyBDs9WqzSppA" name="klijent povlaci zahtev" target="_OdaJAHSLEeyBDs9WqzSppA" source="_Udy9IHSWEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VxeykXSWEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Vxn8gHSWEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wwsVkHSXEeyBDs9WqzSppA" target="_85EywHSOEeyBDs9WqzSppA" source="_Udy9IHSWEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wwsVkXSXEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_wwsVknSXEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qpmJkHSZEeyBDs9WqzSppA" name="ima dovoljno ponuda" target="_qpc_oHSZEeyBDs9WqzSppA" source="_ZadoQHSSEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qpmJkXSZEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_qpmJknSZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3JD68HSZEeyBDs9WqzSppA" name="kupac zadovoljan brojem ponuda" target="_qpc_oHSZEeyBDs9WqzSppA" source="_dAFZMHSUEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3JD68XSZEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3JD68nSZEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MqFMYHSaEeyBDs9WqzSppA" target="_D7-pQHSZEeyBDs9WqzSppA" source="_qpc_oHSZEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MqFMYXSaEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_MqFMYnSaEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dCDq8HSbEeyBDs9WqzSppA" target="_doeKsHSbEeyBDs9WqzSppA" source="_D7-pQHSZEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dCDq8XSbEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_dCDq8nSbEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JuLKAHScEeyBDs9WqzSppA" name="Kupac zavrsava proces" target="_81fQF3SKEeyBDs9WqzSppA" source="_doeKsHSbEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JuLKAXScEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_JuLKAnScEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_z-8oDHScEeyBDs9WqzSppA" name="Kupcu odgovara ponuda" target="_5bM1UHScEeyBDs9WqzSppA" source="_doeKsHSbEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_z-8oDXScEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_z-8oDnScEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_maDNsHSeEeyBDs9WqzSppA" target="_0nLGoHSREeyBDs9WqzSppA" source="_85EywHSOEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_maDNsXSeEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_maDNsnSeEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6WRPHHSfEeyBDs9WqzSppA" target="_uLgs8HSgEeyBDs9WqzSppA" source="_doeKsHSbEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6WRPHXSfEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6WRPHnSfEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6aNecHSgEeyBDs9WqzSppA" target="_2fyQQHSgEeyBDs9WqzSppA" source="_uLgs8HSgEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6aNecXSgEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6aNecnSgEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Bg0UwHShEeyBDs9WqzSppA" target="_COghMHShEeyBDs9WqzSppA" source="_2fyQQHSgEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Bg0UwXShEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_Bg0UwnShEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VQSwGHShEeyBDs9WqzSppA" target="_VQSwEHShEeyBDs9WqzSppA" source="_COghMHShEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VQSwGXShEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VQSwGnShEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gC-2kHShEeyBDs9WqzSppA" name="kupac nije zadovoljan odgovorom" target="_D7-pQHSZEeyBDs9WqzSppA" source="_VQSwEHShEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gC-2kXShEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_gC-2knShEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hqwFoHShEeyBDs9WqzSppA" name="kupac zadovoljan odgovorom" target="_5bM1UHScEeyBDs9WqzSppA" source="_VQSwEHShEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hqwFoXShEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_hqwFonShEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GdVAIHSjEeyBDs9WqzSppA" target="_GdLPIHSjEeyBDs9WqzSppA" source="_5bM1UHScEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GdVAIXSjEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_GdVAInSjEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_h68L0HSjEeyBDs9WqzSppA" target="_i8YasHSjEeyBDs9WqzSppA" source="_hNIDkHSjEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_h68L0XSjEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_h68L0nSjEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_n5TArHSjEeyBDs9WqzSppA" target="_poOnoHSjEeyBDs9WqzSppA" source="_hNIDkHSjEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_n5TArXSjEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_n5TArnSjEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2XRGHHSjEeyBDs9WqzSppA" target="_2XRGEHSjEeyBDs9WqzSppA" source="_GdLPIHSjEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2XRGHXSjEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_2XRGHnSjEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3IvmUHSjEeyBDs9WqzSppA" target="_hNIDkHSjEeyBDs9WqzSppA" source="_2XRGEHSjEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3IvmUXSjEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_3IvmUnSjEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HYcvKHSkEeyBDs9WqzSppA" target="_HYcvIHSkEeyBDs9WqzSppA" source="_poOnoHSjEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HYmgIHSkEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_HYmgIXSkEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_JPZCoHSkEeyBDs9WqzSppA" target="_HYcvIHSkEeyBDs9WqzSppA" source="_i8YasHSjEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JPZCoXSkEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_JPZConSkEeyBDs9WqzSppA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VLCVQHSkEeyBDs9WqzSppA" target="_OdaJAHSLEeyBDs9WqzSppA" source="_HYcvIHSkEeyBDs9WqzSppA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_VLCVQXSkEeyBDs9WqzSppA"/>
        <condition xmi:type="expression:Expression" xmi:id="_VLCVQnSkEeyBDs9WqzSppA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_81fQK3SKEeyBDs9WqzSppA" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_81fQLHSKEeyBDs9WqzSppA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_81fQLXSKEeyBDs9WqzSppA">
        <name xmi:type="expression:Expression" xmi:id="_81fQLnSKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_81fQL3SKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_81fQMHSKEeyBDs9WqzSppA">
        <name xmi:type="expression:Expression" xmi:id="_81fQMXSKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_81fQMnSKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_81fQM3SKEeyBDs9WqzSppA">
        <name xmi:type="expression:Expression" xmi:id="_81fQNHSKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_81fQNXSKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_81fQNnSKEeyBDs9WqzSppA">
        <name xmi:type="expression:Expression" xmi:id="_81fQN3SKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_81fQOHSKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_81fQOXSKEeyBDs9WqzSppA">
        <name xmi:type="expression:Expression" xmi:id="_81fQOnSKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_81fQO3SKEeyBDs9WqzSppA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_81fQPHSKEeyBDs9WqzSppA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_81fQPXSKEeyBDs9WqzSppA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_81fQPnSKEeyBDs9WqzSppA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_81fQP3SKEeyBDs9WqzSppA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_81fQQHSKEeyBDs9WqzSppA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_81fQQXSKEeyBDs9WqzSppA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_81fQQnSKEeyBDs9WqzSppA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_81fQQ3SKEeyBDs9WqzSppA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_81fQRHSKEeyBDs9WqzSppA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_81fQRXSKEeyBDs9WqzSppA" type="Process" element="_81fQEHSKEeyBDs9WqzSppA" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_81fQRnSKEeyBDs9WqzSppA" type="2007" element="_81fQEXSKEeyBDs9WqzSppA">
      <children xmi:type="notation:DecorationNode" xmi:id="_81fQR3SKEeyBDs9WqzSppA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_81fQSHSKEeyBDs9WqzSppA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_81fQSXSKEeyBDs9WqzSppA" type="3007" element="_81fQEnSKEeyBDs9WqzSppA">
          <children xmi:type="notation:DecorationNode" xmi:id="_81fQSnSKEeyBDs9WqzSppA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_81fQS3SKEeyBDs9WqzSppA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_81fQTHSKEeyBDs9WqzSppA" type="3005" element="_81fQF3SKEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_81fQTXSKEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_81fQTnSKEeyBDs9WqzSppA" x="99" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_81fQT3SKEeyBDs9WqzSppA" type="3002" element="_81fQE3SKEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_81fQUHSKEeyBDs9WqzSppA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_81fQUXSKEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_81fQUnSKEeyBDs9WqzSppA" x="48" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LP8HdHSLEeyBDs9WqzSppA" type="3008" element="_LP8HcHSLEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_LQFRYHSLEeyBDs9WqzSppA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_LQFRYXSLEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LP8HdXSLEeyBDs9WqzSppA" x="441" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OdaJBHSLEeyBDs9WqzSppA" type="3003" element="_OdaJAHSLEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_OdaJBnSLEeyBDs9WqzSppA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_OdaJB3SLEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OdaJBXSLEeyBDs9WqzSppA" x="1106" y="27"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZDdhsHSLEeyBDs9WqzSppA" type="3027" element="_ZDbsgHSLEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZDdhsnSLEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZDdhsXSLEeyBDs9WqzSppA" x="251" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2_i6-XSLEeyBDs9WqzSppA" type="3027" element="_2_i68HSLEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2_i6-3SLEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2_i6-nSLEeyBDs9WqzSppA" x="572" y="17" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HlSlOXSMEeyBDs9WqzSppA" type="3027" element="_HlSlMHSMEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HlSlO3SMEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HlSlOnSMEeyBDs9WqzSppA" x="572" y="136" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_SrQ0HXSMEeyBDs9WqzSppA" type="3005" element="_SrQ0EHSMEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_SrQ0H3SMEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SrQ0HnSMEeyBDs9WqzSppA" x="764" y="131" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zP_qlHSMEeyBDs9WqzSppA" type="3008" element="_zP_qkHSMEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_zP_qlnSMEeyBDs9WqzSppA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_zP_ql3SMEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zP_qlXSMEeyBDs9WqzSppA" x="973" y="141"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XhoQqXSNEeyBDs9WqzSppA" type="3027" element="_XhoQoHSNEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XhoQq3SNEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XhoQqnSNEeyBDs9WqzSppA" x="935" y="255" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_bqNA2XSTEeyBDs9WqzSppA" type="3027" element="_bqNA0HSTEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_bqNA23STEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bqNA2nSTEeyBDs9WqzSppA" x="175" y="388" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QS2RnXSUEeyBDs9WqzSppA" type="3005" element="_QS2RkHSUEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QS2Rn3SUEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QS2RnnSUEeyBDs9WqzSppA" x="441" y="388" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dAPKM3SUEeyBDs9WqzSppA" type="3008" element="_dAFZMHSUEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dAPKNXSUEeyBDs9WqzSppA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dAPKNnSUEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dAPKNHSUEeyBDs9WqzSppA" x="689" y="443"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_M1HUjXSWEeyBDs9WqzSppA" type="3005" element="_M1HUgHSWEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_M1HUj3SWEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_M1HUjnSWEeyBDs9WqzSppA" x="859" y="428" width="146" height="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ud8uI3SWEeyBDs9WqzSppA" type="3008" element="_Udy9IHSWEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ud8uJXSWEeyBDs9WqzSppA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ud8uJnSWEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ud8uJHSWEeyBDs9WqzSppA" x="1068" y="443" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D7_QUHSZEeyBDs9WqzSppA" type="3027" element="_D7-pQHSZEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D7_3YHSZEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7_QUXSZEeyBDs9WqzSppA" x="756" y="676" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_qpc_qXSZEeyBDs9WqzSppA" type="3027" element="_qpc_oHSZEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_qpc_q3SZEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qpc_qnSZEeyBDs9WqzSppA" x="481" y="666" width="160" height="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dofY0HSbEeyBDs9WqzSppA" type="3008" element="_doeKsHSbEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dofY0nSbEeyBDs9WqzSppA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dofY03SbEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dofY0XSbEeyBDs9WqzSppA" x="962" y="674" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uLh7EXSgEeyBDs9WqzSppA" type="3005" element="_uLgs8HSgEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uLh7E3SgEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uLh7EnSgEeyBDs9WqzSppA" x="1098" y="657" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_COghPXShEeyBDs9WqzSppA" type="3005" element="_COghMHShEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_COghP3ShEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_COghPnShEeyBDs9WqzSppA" x="1301" y="588" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VQSwFHShEeyBDs9WqzSppA" type="3009" element="_VQSwEHShEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_VQSwFnShEeyBDs9WqzSppA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_VQSwF3ShEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VQSwFXShEeyBDs9WqzSppA" x="1383" y="749"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_i8YavXSjEeyBDs9WqzSppA" type="3005" element="_i8YasHSjEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_i8Yav3SjEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_i8YavnSjEeyBDs9WqzSppA" x="1501" y="777" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HYcvJHSkEeyBDs9WqzSppA" type="3009" element="_HYcvIHSkEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HYcvJnSkEeyBDs9WqzSppA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HYcvJ3SkEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HYcvJXSkEeyBDs9WqzSppA" x="1611" y="386"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_81fQU3SKEeyBDs9WqzSppA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_81fQVHSKEeyBDs9WqzSppA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_81fQVXSKEeyBDs9WqzSppA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_81fQVnSKEeyBDs9WqzSppA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_81fQV3SKEeyBDs9WqzSppA" x="23" y="10" width="1731" height="907"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="__sVhYHSKEeyBDs9WqzSppA" type="3007" element="__sLwYHSKEeyBDs9WqzSppA">
          <children xmi:type="notation:DecorationNode" xmi:id="__sVhZXSKEeyBDs9WqzSppA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="__sVhZnSKEeyBDs9WqzSppA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_85EyzXSOEeyBDs9WqzSppA" type="3005" element="_85EywHSOEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_85Eyz3SOEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_85EyznSOEeyBDs9WqzSppA" x="53" y="115" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZadoRHSSEeyBDs9WqzSppA" type="3008" element="_ZadoQHSSEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZadoRnSSEeyBDs9WqzSppA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ZadoR3SSEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZadoRXSSEeyBDs9WqzSppA" x="327" y="27"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0nLGqXSREeyBDs9WqzSppA" type="3027" element="_0nLGoHSREeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0nLGq3SREeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0nLGqnSREeyBDs9WqzSppA" x="279" y="115" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5bOqgHScEeyBDs9WqzSppA" type="3005" element="_5bM1UHScEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5bOqgnScEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5bOqgXScEeyBDs9WqzSppA" x="973" y="45" width="180" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2fyQTXSgEeyBDs9WqzSppA" type="3005" element="_2fyQQHSgEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2fyQT3SgEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2fyQTnSgEeyBDs9WqzSppA" x="1250" y="45" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GdLPKXSjEeyBDs9WqzSppA" type="3027" element="_GdLPIHSjEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GdLPK3SjEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GdLPKnSjEeyBDs9WqzSppA" x="859" y="222" width="184" height="92"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hNIDlHSjEeyBDs9WqzSppA" type="3009" element="_hNIDkHSjEeyBDs9WqzSppA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hNIDlnSjEeyBDs9WqzSppA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hNIDl3SjEeyBDs9WqzSppA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hNIDlXSjEeyBDs9WqzSppA" x="1329" y="245"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_poOnrXSjEeyBDs9WqzSppA" type="3005" element="_poOnoHSjEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_poOnr3SjEeyBDs9WqzSppA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_poOnrnSjEeyBDs9WqzSppA" x="1535" y="317" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2XRGGXSjEeyBDs9WqzSppA" type="3027" element="_2XRGEHSjEeyBDs9WqzSppA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2XRGG3SjEeyBDs9WqzSppA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2XRGGnSjEeyBDs9WqzSppA" x="1118" y="243" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="__sVhYXSKEeyBDs9WqzSppA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="__sVhYnSKEeyBDs9WqzSppA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="__sVhY3SKEeyBDs9WqzSppA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="__sVhZ3SKEeyBDs9WqzSppA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="__sVhZHSKEeyBDs9WqzSppA" x="23" y="907" width="1731" height="428"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_81fQWHSKEeyBDs9WqzSppA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_81fQWXSKEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_81fQWnSKEeyBDs9WqzSppA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_81fQW3SKEeyBDs9WqzSppA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_81fQXHSKEeyBDs9WqzSppA" width="1833" height="321"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_81fQXXSKEeyBDs9WqzSppA"/>
    <edges xmi:type="notation:Connector" xmi:id="_81fQXnSKEeyBDs9WqzSppA" type="4001" element="_81fQKHSKEeyBDs9WqzSppA" source="_81fQT3SKEeyBDs9WqzSppA" target="_81fQTHSKEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_81fQX3SKEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_81fQYHSKEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_81fQYXSKEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_81fQYnSKEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_js2iQ3SLEeyBDs9WqzSppA" type="4001" element="_js2iQHSLEeyBDs9WqzSppA" source="_81fQTHSKEeyBDs9WqzSppA" target="_ZDdhsHSLEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_js2iRnSLEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_js2iR3SLEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_js2iRHSLEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_js2iRXSLEeyBDs9WqzSppA" points="[0, -8, -130, -6]$[70, -8, -60, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_js2iSHSLEeyBDs9WqzSppA" id="(1.0,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pZUV03SLEeyBDs9WqzSppA" type="4001" element="_pZUV0HSLEeyBDs9WqzSppA" source="_ZDdhsHSLEeyBDs9WqzSppA" target="_LP8HdHSLEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pZUV1nSLEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pZUV13SLEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pZUV1HSLEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pZUV1XSLEeyBDs9WqzSppA" points="[15, -3, -91, 0]$[85, -3, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pZUV2HSLEeyBDs9WqzSppA" id="(0.875,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__G9G83SLEeyBDs9WqzSppA" type="4001" element="__G9G8HSLEeyBDs9WqzSppA" source="_LP8HdHSLEeyBDs9WqzSppA" target="_2_i6-XSLEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__G9G9nSLEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__G9G93SLEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__G9G9HSLEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__G9G9XSLEeyBDs9WqzSppA" points="[16, -6, -128, 44]$[113, -61, -31, -11]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__G9G-HSLEeyBDs9WqzSppA" id="(0.22142857142857142,0.3142857142857143)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__2K9Y3SLEeyBDs9WqzSppA" type="4001" element="__2K9YHSLEeyBDs9WqzSppA" source="_2_i6-XSLEeyBDs9WqzSppA" target="_OdaJBHSLEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__2K9ZnSLEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__2K9Z3SLEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__2K9ZHSLEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__2K9ZXSLEeyBDs9WqzSppA" points="[17, -20, -485, -15]$[497, -20, -5, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__2K9aHSLEeyBDs9WqzSppA" id="(0.8785714285714286,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KjTOcHSMEeyBDs9WqzSppA" type="4001" element="_KjKEgHSMEeyBDs9WqzSppA" source="_LP8HdHSLEeyBDs9WqzSppA" target="_HlSlOXSMEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KjTOc3SMEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KjTOdHSMEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KjTOcXSMEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KjTOcnSMEeyBDs9WqzSppA" points="[-4, -2, -134, -87]$[110, 86, -20, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KjTOdXSMEeyBDs9WqzSppA" id="(1.0,0.6046511627906976)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KjTOdnSMEeyBDs9WqzSppA" id="(0.14285714285714285,0.5428571428571428)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VMh283SMEeyBDs9WqzSppA" type="4001" element="_VMh28HSMEeyBDs9WqzSppA" source="_HlSlOXSMEeyBDs9WqzSppA" target="_SrQ0HXSMEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VMh29nSMEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VMh293SMEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VMh29HSMEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VMh29XSMEeyBDs9WqzSppA" points="[0, 7, -88, -21]$[69, 7, -19, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VMh2-HSMEeyBDs9WqzSppA" id="(1.0,0.38571428571428573)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VMh2-XSMEeyBDs9WqzSppA" id="(0.11875,0.75)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zpw1cHSMEeyBDs9WqzSppA" type="4001" element="_zpwOYHSMEeyBDs9WqzSppA" source="_SrQ0HXSMEeyBDs9WqzSppA" target="_zP_qlHSMEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zpxcgHSMEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zpxcgXSMEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zpw1cXSMEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zpw1cnSMEeyBDs9WqzSppA" points="[0, 9, -70, -1]$[64, -5, -6, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_zpzRsHSMEeyBDs9WqzSppA" id="(1.0,0.3625)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DdJOo3SNEeyBDs9WqzSppA" type="4001" element="_DdJOoHSNEeyBDs9WqzSppA" source="_zP_qlHSMEeyBDs9WqzSppA" target="_XhoQqXSNEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DdJOpnSNEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DdJOp3SNEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DdJOpHSNEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DdJOpXSNEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Y7m7UHSNEeyBDs9WqzSppA" type="4001" element="_Y7ip4HSNEeyBDs9WqzSppA" source="_zP_qlHSMEeyBDs9WqzSppA" target="_OdaJBHSLEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Y7m7U3SNEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Y7m7VHSNEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Y7m7UXSNEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Y7m7UnSNEeyBDs9WqzSppA" points="[-11, -18, -116, 109]$[-11, -128, -116, -1]$[90, -128, -15, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Y7owgHSNEeyBDs9WqzSppA" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_U1zHEHSOEeyBDs9WqzSppA" type="4001" element="_U1p9IHSOEeyBDs9WqzSppA" source="_LP8HdHSLEeyBDs9WqzSppA" target="_XhoQqXSNEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_U1zHE3SOEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_U1zHFHSOEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_U1zHEXSOEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_U1zHEnSOEeyBDs9WqzSppA" points="[-26, 11, -506, -182]$[-26, 179, -506, -14]$[451, 179, -29, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_U1zHFXSOEeyBDs9WqzSppA" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_U1zHFnSOEeyBDs9WqzSppA" id="(0.24166666666666667,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GajwE3SPEeyBDs9WqzSppA" type="4001" element="_GajwEHSPEeyBDs9WqzSppA" source="_XhoQqXSNEeyBDs9WqzSppA" target="_85EyzXSOEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GajwFnSPEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GajwF3SPEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GajwFHSPEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GajwFXSPEeyBDs9WqzSppA" points="[-25, 31, 850, -711]$[-25, 85, 850, -657]$[-928, 85, -53, -657]$[-928, 738, -53, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Gas6AHSPEeyBDs9WqzSppA" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Gas6AXSPEeyBDs9WqzSppA" id="(0.9071428571428571,0.05714285714285714)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_25BikHSTEeyBDs9WqzSppA" type="4001" element="_25A7gHSTEeyBDs9WqzSppA" source="_ZadoRHSSEeyBDs9WqzSppA" target="_bqNA2XSTEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_25Bik3STEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_25CJoHSTEeyBDs9WqzSppA" x="30" y="-68"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_25BikXSTEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_25BiknSTEeyBDs9WqzSppA" points="[-22, -31, 159, 238]$[-22, -194, 159, 75]$[-157, -194, 24, 75]$[-157, -228, 24, 41]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_25DXwHSTEeyBDs9WqzSppA" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_25DXwXSTEeyBDs9WqzSppA" id="(0.0875,0.4875)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3YKVo3STEeyBDs9WqzSppA" type="4001" element="_3YKVoHSTEeyBDs9WqzSppA" source="_0nLGqXSREeyBDs9WqzSppA" target="_ZadoRHSSEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3YKVpnSTEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3YKVp3STEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3YKVpHSTEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3YKVpXSTEeyBDs9WqzSppA" points="[-81, -29, 0, 74]$[-81, -81, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3YKVqHSTEeyBDs9WqzSppA" id="(1.0,0.4142857142857143)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Rzou43SUEeyBDs9WqzSppA" type="4001" element="_Rzou4HSUEeyBDs9WqzSppA" source="_bqNA2XSTEeyBDs9WqzSppA" target="_QS2RnXSUEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Rzou5nSUEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Rzou53SUEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Rzou5HSUEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Rzou5XSUEeyBDs9WqzSppA" points="[0, 5, -99, 0]$[87, 3, -12, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Rzou6HSUEeyBDs9WqzSppA" id="(1.0,0.3625)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Rzou6XSUEeyBDs9WqzSppA" id="(0.12,0.38)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ePE743SUEeyBDs9WqzSppA" type="4001" element="_ePE74HSUEeyBDs9WqzSppA" source="_QS2RnXSUEeyBDs9WqzSppA" target="_dAPKM3SUEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ePE75nSUEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ePE753SUEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ePE75HSUEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ePE75XSUEeyBDs9WqzSppA" points="[0, 7, -116, 0]$[95, 7, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ePE76HSUEeyBDs9WqzSppA" id="(1.0,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_C3-LY3SVEeyBDs9WqzSppA" type="4001" element="_C3-LYHSVEeyBDs9WqzSppA" source="_dAPKM3SUEeyBDs9WqzSppA" target="_XhoQqXSNEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_C3-LZnSVEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_C3-LZ3SVEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_C3-LZHSVEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_C3-LZXSVEeyBDs9WqzSppA" points="[-22, -30, -286, 216]$[-22, -162, -286, 84]$[264, -162, 0, 84]$[264, -216, 0, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_C3-LaHSVEeyBDs9WqzSppA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Lczdw3SWEeyBDs9WqzSppA" type="4001" element="_LczdwHSWEeyBDs9WqzSppA" source="_dAPKM3SUEeyBDs9WqzSppA" target="_M1HUjXSWEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LczdxnSWEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Lczdx3SWEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LczdxHSWEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LczdxXSWEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UHyQ43SWEeyBDs9WqzSppA" type="4001" element="_UHyQ4HSWEeyBDs9WqzSppA" source="_M1HUjXSWEeyBDs9WqzSppA" target="_Ud8uI3SWEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UHyQ5nSWEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UHyQ53SWEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UHyQ5HSWEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UHyQ5XSWEeyBDs9WqzSppA" points="[73, 0, -84, 0]$[136, 0, -21, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Vxn8gXSWEeyBDs9WqzSppA" type="4001" element="_VxeykHSWEeyBDs9WqzSppA" source="_Ud8uI3SWEeyBDs9WqzSppA" target="_OdaJBHSLEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Vxn8hHSWEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Vxn8hXSWEeyBDs9WqzSppA" x="-33" y="-22"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Vxn8gnSWEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Vxn8g3SWEeyBDs9WqzSppA" points="[0, -6, -23, 411]$[73, -6, 50, 411]$[73, -154, 50, 263]$[20, -154, -3, 263]$[20, -414, -3, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Vxn8hnSWEeyBDs9WqzSppA" id="(1.0,0.627906976744186)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Vxn8h3SWEeyBDs9WqzSppA" id="(0.5666666666666667,0.8666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wwsVk3SXEeyBDs9WqzSppA" type="4001" element="_wwsVkHSXEeyBDs9WqzSppA" source="_Ud8uI3SWEeyBDs9WqzSppA" target="_85EyzXSOEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wwsVlnSXEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wwsVl3SXEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wwsVlHSXEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wwsVlXSXEeyBDs9WqzSppA" points="[-27, 6, 961, -577]$[-27, 183, 961, -400]$[-959, 183, 29, -400]$[-959, 548, 29, -35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ww2GkHSXEeyBDs9WqzSppA" id="(1.0,0.7209302325581395)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qpv6kHSZEeyBDs9WqzSppA" type="4001" element="_qpmJkHSZEeyBDs9WqzSppA" source="_ZadoRHSSEeyBDs9WqzSppA" target="_qpc_qXSZEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qpv6k3SZEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qpv6lHSZEeyBDs9WqzSppA" x="-22" y="-6"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qpv6kXSZEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qpv6knSZEeyBDs9WqzSppA" points="[13, -8, -200, 120]$[180, -8, -33, 120]$[180, -88, -33, 40]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3JD683SZEeyBDs9WqzSppA" type="4001" element="_3JD68HSZEeyBDs9WqzSppA" source="_dAPKM3SUEeyBDs9WqzSppA" target="_qpc_qXSZEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3JD69nSZEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3JD693SZEeyBDs9WqzSppA" x="19" y="19"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3JD69HSZEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3JD69XSZEeyBDs9WqzSppA" points="[-22, 14, 146, -192]$[-22, 99, 146, -107]$[-160, 99, 8, -107]$[-160, 194, 8, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3JD6-HSZEeyBDs9WqzSppA" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3JD6-XSZEeyBDs9WqzSppA" id="(0.51875,0.15)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MqOWUHSaEeyBDs9WqzSppA" type="4001" element="_MqFMYHSaEeyBDs9WqzSppA" source="_qpc_qXSZEeyBDs9WqzSppA" target="_D7_QUHSZEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MqOWU3SaEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MqOWVHSaEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MqOWUXSaEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MqOWUnSaEeyBDs9WqzSppA" points="[0, 19, -139, 4]$[115, 19, -24, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MqOWVXSaEeyBDs9WqzSppA" id="(1.0,0.3875)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MqOWVnSaEeyBDs9WqzSppA" id="(0.2,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dCDq83SbEeyBDs9WqzSppA" type="4001" element="_dCDq8HSbEeyBDs9WqzSppA" source="_D7_QUHSZEeyBDs9WqzSppA" target="_dofY0HSbEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dCDq9nSbEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dCDq93SbEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dCDq9HSbEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dCDq9XSbEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JuLKA3ScEeyBDs9WqzSppA" type="4001" element="_JuLKAHScEeyBDs9WqzSppA" source="_dofY0HSbEeyBDs9WqzSppA" target="_81fQTHSKEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JuLKBnScEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JuLKB3ScEeyBDs9WqzSppA" x="-566" y="12"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JuLKBHScEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JuLKBXScEeyBDs9WqzSppA" points="[-22, 12, 858, 603]$[-22, 44, 858, 635]$[-97, 44, 783, 635]$[-97, 310, 783, 901]$[-971, 310, -91, 901]$[-971, -522, -91, 69]$[-846, -522, 34, 69]$[-846, -585, 34, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JuLKCHScEeyBDs9WqzSppA" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Qlf8QHSeEeyBDs9WqzSppA" id="(0.21666666666666667,0.9)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_z_Fx8HScEeyBDs9WqzSppA" type="4001" element="_z-8oDHScEeyBDs9WqzSppA" source="_dofY0HSbEeyBDs9WqzSppA" target="_5bOqgHScEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_z_Fx83ScEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_z_Fx9HScEeyBDs9WqzSppA" x="-7" y="13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_z_Fx8XScEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_z_Fx8nScEeyBDs9WqzSppA" points="[0, 22, 257, -149]$[0, 73, 257, -98]$[-252, 73, 5, -98]$[-252, 146, 5, -25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_maDNs3SeEeyBDs9WqzSppA" type="4001" element="_maDNsHSeEeyBDs9WqzSppA" source="_85EyzXSOEeyBDs9WqzSppA" target="_0nLGqXSREeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_maDNtnSeEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_maDNt3SeEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_maDNtHSeEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_maDNtXSeEeyBDs9WqzSppA" points="[0, 0, -115, -40]$[88, 34, -27, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_maDNuHSeEeyBDs9WqzSppA" id="(1.0,0.4142857142857143)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_maDNuXSeEeyBDs9WqzSppA" id="(0.19285714285714287,0.38571428571428573)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6WaZAHSfEeyBDs9WqzSppA" type="4001" element="_6WRPHHSfEeyBDs9WqzSppA" source="_dofY0HSbEeyBDs9WqzSppA" target="_uLh7EXSgEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6WaZA3SfEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6WaZBHSfEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6WaZAXSfEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6WaZAnSfEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6aNec3SgEeyBDs9WqzSppA" type="4001" element="_6aNecHSgEeyBDs9WqzSppA" source="_uLh7EXSgEeyBDs9WqzSppA" target="_2fyQTXSgEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6aNednSgEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6aNed3SgEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6aNedHSgEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6aNedXSgEeyBDs9WqzSppA" points="[-51, 29, 9, -154]$[-51, 153, 9, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6aNeeHSgEeyBDs9WqzSppA" id="(1.0,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Bg0Uw3ShEeyBDs9WqzSppA" type="4001" element="_Bg0UwHShEeyBDs9WqzSppA" source="_2fyQTXSgEeyBDs9WqzSppA" target="_COghPXShEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Bg0UxnShEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Bg0Ux3ShEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Bg0UxHShEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Bg0UxXShEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VQSwG3ShEeyBDs9WqzSppA" type="4001" element="_VQSwGHShEeyBDs9WqzSppA" source="_COghPXShEeyBDs9WqzSppA" target="_VQSwFHShEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VQSwHnShEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VQSwH3ShEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VQSwHHShEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VQSwHXShEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gC-2k3ShEeyBDs9WqzSppA" type="4001" element="_gC-2kHShEeyBDs9WqzSppA" source="_VQSwFHShEeyBDs9WqzSppA" target="_D7_QUHSZEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gC-2lnShEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gC-2l3ShEeyBDs9WqzSppA" x="15" y="19"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gC-2lHShEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gC-2lXShEeyBDs9WqzSppA" points="[0, -9, 610, 74]$[71, -9, 681, 74]$[71, -201, 681, -118]$[-610, -201, 0, -118]$[-610, -113, 0, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gC-2mHShEeyBDs9WqzSppA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hqwssHShEeyBDs9WqzSppA" type="4001" element="_hqwFoHShEeyBDs9WqzSppA" source="_VQSwFHShEeyBDs9WqzSppA" target="_5bOqgHScEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hqwss3ShEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hqwstHShEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hqwssXShEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hqwssnShEeyBDs9WqzSppA" points="[19, -12, 306, -158]$[46, -12, 333, -158]$[46, 228, 333, 82]$[-265, 228, 22, 82]$[-265, 194, 22, 48]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hqyh4HShEeyBDs9WqzSppA" id="(0.3953488372093023,0.9302325581395349)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hqyh4XShEeyBDs9WqzSppA" id="(0.7777777777777778,0.4666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GdVAI3SjEeyBDs9WqzSppA" type="4001" element="_GdVAIHSjEeyBDs9WqzSppA" source="_5bOqgHScEeyBDs9WqzSppA" target="_GdLPKXSjEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GdVAJnSjEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GdVAJ3SjEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GdVAJHSjEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GdVAJXSjEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_h68L03SjEeyBDs9WqzSppA" type="4001" element="_h68L0HSjEeyBDs9WqzSppA" source="_hNIDlHSjEeyBDs9WqzSppA" target="_i8YavXSjEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_h68L1nSjEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_h68L13SjEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_h68L1HSjEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_h68L1XSjEeyBDs9WqzSppA" points="[15, -6, -206, 355]$[199, -6, -22, 355]$[199, -326, -22, 35]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_n5TAr3SjEeyBDs9WqzSppA" type="4001" element="_n5TArHSjEeyBDs9WqzSppA" source="_hNIDlHSjEeyBDs9WqzSppA" target="_poOnrXSjEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_n5TAsnSjEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_n5TAs3SjEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_n5TAsHSjEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_n5TAsXSjEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2XRGH3SjEeyBDs9WqzSppA" type="4001" element="_2XRGHHSjEeyBDs9WqzSppA" source="_GdLPKXSjEeyBDs9WqzSppA" target="_2XRGGXSjEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2XRGInSjEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2XRGI3SjEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2XRGIHSjEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2XRGIXSjEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3IvmU3SjEeyBDs9WqzSppA" type="4001" element="_3IvmUHSjEeyBDs9WqzSppA" source="_2XRGGXSjEeyBDs9WqzSppA" target="_hNIDlHSjEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3IvmVnSjEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3IvmV3SjEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3IvmVHSjEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3IvmVXSjEeyBDs9WqzSppA" points="[0, 0, -92, 21]$[37, 0, -55, 21]$[37, -21, -55, 0]$[71, -21, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_3IvmWHSjEeyBDs9WqzSppA" id="(1.0,0.64)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HYmgInSkEeyBDs9WqzSppA" type="4001" element="_HYcvKHSkEeyBDs9WqzSppA" source="_poOnrXSjEeyBDs9WqzSppA" target="_HYcvJHSkEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HYmgJXSkEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HYmgJnSkEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HYmgI3SkEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HYmgJHSkEeyBDs9WqzSppA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_JPZCo3SkEeyBDs9WqzSppA" type="4001" element="_JPZCoHSkEeyBDs9WqzSppA" source="_i8YavXSjEeyBDs9WqzSppA" target="_HYcvJHSkEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JPZCpnSkEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_JPZCp3SkEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_JPZCpHSkEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JPZCpXSkEeyBDs9WqzSppA" points="[0, 0, -37, -181]$[30, 167, -7, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_JPZCqHSkEeyBDs9WqzSppA" id="(1.0,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_VLCVQ3SkEeyBDs9WqzSppA" type="4001" element="_VLCVQHSkEeyBDs9WqzSppA" source="_HYcvJHSkEeyBDs9WqzSppA" target="_OdaJBHSLEeyBDs9WqzSppA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_VLCVRnSkEeyBDs9WqzSppA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_VLCVR3SkEeyBDs9WqzSppA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_VLCVRHSkEeyBDs9WqzSppA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_VLCVRXSkEeyBDs9WqzSppA" points="[-22, -23, 519, 350]$[-22, -368, 519, 5]$[-519, -368, 22, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VLCVSHSkEeyBDs9WqzSppA" id="(1.0,0.5348837209302325)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VLCVSXSkEeyBDs9WqzSppA" id="(0.23333333333333334,0.3)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
